// <auto-generated />
namespace CustomerTable.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class try5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(try5));
        
        string IMigrationMetadata.Id
        {
            get { return "201708011210233_try5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
